const data = {
  products: [
    {
      name: "Nike Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Nike Slim pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 110,
      countInStock: 10,
      brand: "Nike",
      rating: 4.0,
      numReviews: 15,
      description: "high quality pant",
    },
    {
      name: "Adidas Fit Pant",
      slug: "Adidas-fit-pant",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 5.0,
      numReviews: 20,
      description: "high quality product",
    },
    {
      name: "Adidas Fit shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 90,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality shirt",
    },
  ],
};

export default data;
